# Generated by Django 2.0.4 on 2018-04-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fadu_test_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testerrorlogs',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='testiologs',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='testsmartlogs',
            name='test_cases',
        ),
        migrations.DeleteModel(
            name='TestCases',
        ),
        migrations.DeleteModel(
            name='TestErrorLogs',
        ),
        migrations.DeleteModel(
            name='TestIoLogs',
        ),
        migrations.DeleteModel(
            name='TestSmartLogs',
        ),
    ]
