# Generated by Django 2.0.4 on 2018-04-24 05:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_group_id', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('configs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestErrorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.TextField()),
                ('test_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.TestCases')),
            ],
        ),
        migrations.CreateModel(
            name='TestIoLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Percentile', models.FloatField()),
                ('Wr_iops', models.FloatField()),
                ('Wr_throughput', models.FloatField()),
                ('Wr_latency', models.FloatField()),
                ('Rd_iops', models.FloatField()),
                ('Rd_throughput', models.FloatField()),
                ('Rd_latency', models.FloatField()),
                ('test_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.TestCases')),
            ],
        ),
        migrations.CreateModel(
            name='TestLogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('test_suit_id', models.IntegerField()),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestSmartLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Data_units_read', models.IntegerField()),
                ('test_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.TestCases')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
