# Generated by Django 2.0.4 on 2018-04-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Test_error_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.TextField()),
                ('test_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Test_cases')),
            ],
        ),
        migrations.CreateModel(
            name='Test_io_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Percentile', models.FloatField()),
                ('Wr_iops', models.FloatField()),
                ('Wr_throughput', models.FloatField()),
                ('Wr_latency', models.FloatField()),
                ('Rd_iops', models.FloatField()),
                ('Rd_throughput', models.FloatField()),
                ('Rd_latency', models.FloatField()),
                ('test_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Test_cases')),
            ],
        ),
        migrations.CreateModel(
            name='Test_smart_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Data_units_read', models.IntegerField()),
                ('test_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Test_cases')),
            ],
        ),
    ]
