# Generated by Django 2.0.4 on 2018-04-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='testcases',
            name='Test_group_id',
            field=models.IntegerField(),
        ),
    ]
